- name: Add a host for prometheus-node you can custom at group_vars
  ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ ip_node_prom_dua }}"
      create: yes

- name: Add a host for prometheus-node you can custom at group_vars
  lineinfile: 
    dest: /etc/hosts
    line: '{{ item }}'
  with_items: 
    - "{{ ip_node_prom_satu }}"
    - "{{ ip_node_prom_dua }}"

- name: Download and extract Node Exporter
  get_url:
    url: "{{ download_version_node }}"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter to Folder Opt
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt/"
    remote_src: yes

#- name: Install Node_Exporter
 # shell: curl -s https://github.com/prometheus/prometheus/releases/download/v2.3.2/prometheus-2.3.2.linux-amd64.tar.gz | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi -
  #args:
   #   chdir: "/usr/local/bin"
    #  warn: no


#- name: Unarchive a file that is already on the remote machine
 # ansible.builtin.unarchive:
  #  src: /usr/local/bin/node_exporter-1.7.0.linux-amd64
   # dest: /usr/local/bin
    #remote_src: yes      

  #- name: Creating /dir1 & /dir2
   # file:
    #  path: "{{ item }}"
     # state: directory
    #with_items:
    # - /dir1
    # - /dir2


#- name: UNZIPPING the files
 # unarchive:
  #  src: "/usr/local/bin/"
   # dest: "/usr/local/bin/node_exporter/"
    #copy: no
  #with_fileglob:
  #- "/usr/local/bin/*.tar.gz"

#- name: Extract archive.tgz into /usr/bin
  #ansible.builtin.unarchive:
   # src: /usr/bin/ 
    #dest: /usr/bin/
    #remote_src: yes
  #with_fileglob: "node_exporter-*"

- name: move node_exporter to folder usr/bin
  command: mv /opt/node_exporter-1.7.0.linux-amd64/node_exporter /usr/bin/

- name: copy node_exporter to usr/local/bin
  copy:
    src: /usr/bin/node_exporter
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes

- name: Change file permission etc
  file:
    path: /usr/bin/
    owner: root
    group: root
    mode: '0775'  

#- name: copy node_exporter to usr/bin
  #copy:
    #src: /usr/local/bin/node_exporter
    #dest: /usr/bin/
    #mode: '0755'


#- name: Removing dir_cache & file_cache
  #file:
      #path: "{{ item }}"
      #state: absent
  #with_items:
     #- /usr/bin/node_exporter-1.7.0.linux-amd64.tar.gz
     #- /usr/bin/node_exporter-1.7.0.linux-amd64

- name: Menambahkan file konfigurasi ke node_exporter.service
  copy:
    src: ../templates/node_exporter.service
    dest: /etc/systemd/system/

- name: Ensure 'node_exporter' userxists
  user:
    name: node_exporter
    state: present


#- name: Reload services with systemd
 # systemd:
  #   name: node_exporter.service 
   #  state: reloaded
    # daemon_reload: true

- name: Reload daemon system
  ansible.builtin.systemd:
    daemon_reload: yes

- name: service always started
  systemd:
    name: node_exporter
    state: started
    enabled: yes
