
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "server33-11"
  config.vm.network "private_network", ip: "192.168.33.11",virtualbox__intnet: "gcptest-network"
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--natnet1", "10.4/16"]
  end
end


