apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: webpage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webpage-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 1
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 1Mi