- name: Prometheus server-groupadd
  group:
    name: prometheus
    state: present  
 
- name: Prometheus server-useradd
  user:
    name: prometheus   
    state: present     

- name: Prometheus server-Creating Directory
  file:
     path: "{{ item }}"
     state: directory
  with_items:
     - /var/lib/prometheus
     - /tmp/prometheus

- name: Prometheus server-Create rules
  shell: for i in rules rules.d files_sd; do sudo mkdir -p /etc/prometheus/${i}; done

- name: Prometheus server-INSTALL
  shell: curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi -
  args:
      chdir: "/tmp/prometheus"
      warn: no

- name: Prometheus server-Extract archive.tgz 
  ansible.builtin.unarchive:
    src: /tmp/prometheus/prometheus-2.39.1.linux-amd64.tar.gz
    dest: /tmp/prometheus
    remote_src: yes

- name: Prometheus server-prometheus move to folder
  command: mv /tmp/prometheus/prometheus-2.39.1.linux-amd64/prometheus /usr/local/bin/

- name: Prometheus server-promtool move to folder
  command: mv /tmp/prometheus/prometheus-2.39.1.linux-amd64/promtool /usr/local/bin/

- name: Prometheus server-prometheus.yml move to folder
  command: mv /tmp/prometheus/prometheus-2.39.1.linux-amd64/prometheus.yml /etc/prometheus/

- name: Prometheus server-console move to folder
  command: cp -rf /tmp/prometheus/prometheus-2.39.1.linux-amd64/consoles/ /etc/prometheus/

- name: Prometheus server-console_libraries move to folder
  command: cp -rf /tmp/prometheus/prometheus-2.39.1.linux-amd64/console_libraries/ /etc/prometheus/

- name: copy config
  copy:
    src: ../templates/prometheus.service
    dest: /etc/systemd/system/

- name: Prometheus server-Change file permission etc
  file:
    path: /etc/prometheus/
    owner: prometheus
    group: prometheus
    mode: '0775'

- name: Prometheus server-Change file permission var/lib
  file:
    path: /var/lib/prometheus/
    owner: prometheus
    group: prometheus

- name: Reload daemon system
  ansible.builtin.systemd:
    daemon_reload: yes

- name: starting service
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: DONE
  debug:
    msg: "The Prometheus service Installed successfully"

- name: Check Promtool version
  command: promtool  --version
  register: promVersion
- name: Print Promtool version
  debug:
    msg: "Promtool Version: {{ promVersion.stdout }}"

- name: Check Prometheus version
  command: prometheus  --version
  register: prometVersion
- name: Print Prometheus version
  debug:
    msg: "Prometheus Version: {{ prometVersion.stdout }}"



- name: Grafana server-Keyadd
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: Grafana server-Repoadd
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes

- name: Grafana server-Install 
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Reload daemon system
  ansible.builtin.systemd:
    daemon_reload: yes

- name: service always started
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: DONE
  debug:
    msg: "The Grafana Server Installed successfully"


